version: "3.7"

services:
  php:
    build:
      context: ./docker/images/php
    container_name: iot-php
    env_file:
      - ./env/production/.env
    volumes:
      - "./web:/var/www/html"
      - "./docker/dashboard:/var/www/dashboard"
    depends_on:
      - mariadb

  nginx:
    build:
      context: ./docker
      dockerfile: ./images/nginx-push-stream/Dockerfile
    container_name: iot-nginx
    ports:
      - "${WEBSERVER_PORT}:80"
    volumes:
      - "./web:/var/www/html"
      - "./docker/config/nginx/conf.d:/etc/nginx/conf.d"
      - "./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./docker/dashboard:/var/www/dashboard"
    depends_on:
      - php

  mariadb:
    image: mariadb:latest
    container_name: iot-mariadb
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - "./docker/config/mariadb:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: iot-phpmyadmin
    environment:
      - "PMA_HOST=mariadb"
      - "PMA_PORT=${MYSQL_PORT}"
      - "PMA_ABSOLUTE_URI=http://localhost/phpmyadmin"
    volumes:
      - "./docker/config/phpmyadmin/sessions:/sessions"

  tunnel:
    build:
      context: ./docker/images/tunnel
    container_name: iot-tunnel
    environment:
      - "WEBSERVER_PORT=${WEBSERVER_PORT}"
      - "TUNNEL_SUBDOMAIN=yanisdeplazes"
    depends_on:
      - nginx

  vite:
    image: node:latest
    container_name: iot-vite
    working_dir: /app
    volumes:
      - "./web/src/frontend:/app"
    ports:
      - "5173:5173"
    command: sh -c "npm i && npm run dev"
